### ISSUE TITLE
Zugang zum FEMS

### ISSUE THREAD

**Issue by Stefan231278** [OpenEMS/openems-modbus-master#1]

**Comment by Stefan231278** [comment]
In den Docs, die ich auf der Fenecon-Seite finde, wird das als Hinweis gegeben, wie man auf das FEMS zugreifen kann:

> Die Basis-Adresse für die REST-Zugriffe lautet http://<BENUTZER>:<PASSWORT>@<IP>:8084/rest

http ist das Protokoll

<BENUTZER> ist der Benutzername. Da die Authentifizierung lediglich über das Passwort erfolgt, kann hier ein beliebiger Wert (z. B. "x") angegeben werden

<PASSWORT> ist das Passwort des Benutzers. Der Standard "Gast"-Benutzer im FEMS hat das Passwort "user"

<IP> ist die IP-Adresse des FEMS

8084 ist der Port für die REST/JSON-Api

Wenn Ihr FEMS also die lokale IP-Adresse '192.168.0.23' hat, lautet die Basis-Adresse für REST-Zugriffe http://x:user@192.168.0.23:8084/rest


Ich habe (glaub ich) alles versucht, aber ich bekomme immer die Rückmeldung, dass die Zugangsdaten falsch seien:

{"jsonrpc":"2.0","id":"00000000-0000-0000-0000-000000000000","error":{"code":1003,"message":"Authentication failed","data":[]}}

Ich weiß nicht mehr weiter - können Sie mir da weiterhelfen?

Vielen Dank schon mal

**Comment by sfeilmeier** [comment]
Hallo @Stefan231278,

ich weiß nicht, wie Sie gerade dieses Repository gefunden haben, um uns zu kontaktieren - die richtige Anlaufstelle wäre immer service@fenecon.de. Falls es technischer wird, kann auch das OpenEMS Community-Forum eine gute Quelle sein: https://community.openems.io. Dort geht es aber um OpenEMS generell und nicht (nur) um das FEMS von FENECON.

Bitte geben Sie mir noch Ihre FEMS-Nr. durch - z. B. hier oder per privater Nachricht im Community-Forum - dann kann ich zumindest mal die Software-Version usw. prüfen, da der technische Service über den Jahreswechsel nicht voll besetzt ist.

Viele Grüße,
Stefan Feilmeier

**Comment by Bjnau** [comment]
Hallo, 

ich hoffe, dass mein Post noch gelesen wird, da der Post ja schon einige Jahre alt ist. Auch ich habe das gleich Problem.

http://x:user@192.168.9.39:80/rest/channel/_sum/EssSoc

{"jsonrpc":"2.0","id":"00000000-0000-0000-0000-000000000000","error":{"code":1003,"message":"Authentication failed","data":[]}}

Den Support habe ich bereits angeschrieben.

Vielleicht habe ich auf diesem Wege glück.

**Comment by sfeilmeier** [comment]
Hallo @Bjnau,

hier gibt es eine Anleitung mit Beispielen, wie das Auslesen von Daten funktioniert:
https://docs.fenecon.de/de/_/latest/fems/apis.html#_fems_app_restjson_lese_und_schreibzugriff

Insbesondere ist wichtig zu verstehen, dass die URL [http://x:user@192.168.9.39:80/rest/channel/_sum/EssSoc](http://x:user@192.168.9.39/rest/channel/_sum/EssSoc) im Browser nicht funktioniert. Diese Form der _Basic Authentication_ sollte allgemein aus Sicherheitsgründen nicht mehr verwendet werden und funktioniert deshalb in FEMS/OpenEMS nicht. Stattdessen muss ein echter `GET`-Request genutzt werden, z. B. mit dem Talend API Tester oder `curl`.

Gruß,
Stefan Feilmeier
